services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-asignar_citas}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_ROOT_PASSWORD: example
  back:
    build: ./back
    image: citas-back:latest
    container_name: citas-back
    restart: always
    ports:
      - "${BACK_PORT:-3000}:3000"
    env_file:
      - .env
    enviroments:
      DB_HOST: ${DB_HOST:-db}
      DB_USER: ${DB_USER:-root}
      DB_PORT: ${DB_PORT:-3306}
    depends_on:
      - db
  front:
    build:
      context: ./front
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
    image: citas-front:latest
    container_name: citas-front
    ports:
      - "${FRONT_PORT:-5173}:80"
    env_file:
      - .env
    restart: unless-stopped
  
  

volumes:
  db_data: